import { Geist, Geist_Mono,Roboto } from "next/font/google";
import "./globals.css";
import { ContextProvider } from "./context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const roboto = Roboto({
  subsets: ["latin"],          // required
  weight: ["400", "500", "700"] // choose the weights you need
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={roboto.className}
      >
      <ContextProvider>

        {children}
      </ContextProvider>
      
      </body>
    </html>
  );
}
